apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry-np
  name: registry-np
  namespace: kurl
spec:
  ports:
  - name: registry-np
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: registry
  sessionAffinity: None
  type: NodePort